# Generated by Django 4.2.1 on 2023-05-24 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='categorie',
            new_name='category',
        ),
    ]
